name: Generovat články z RSS

on:
  workflow_dispatch:   # jen ruční spuštění

permissions:
  contents: write      # ← umožní push z GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # výchozí, ale uvádím explicitně

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate site
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL_NAME: gpt-4o-mini
          DAYS_BACK: '5'   # pro test
        run: python scripts/generate.py

      - name: Commit and push changes
        env:
          BRANCH_NAME: ${{ github.ref_name }}   # např. 'main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Manual run: update articles [skip ci]" || echo "No changes to commit"
          # stáhni případné novější commity a přepiš historii čistě
          git pull --rebase origin "$BRANCH_NAME" || true
          git push origin HEAD:"$BRANCH_NAME"
